# yaml-language-server: schema=https://json.schemastore.org/github-action

name: Build
on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: paths
      env:
        PNPM_ROOT: ${{ runner.temp }}/.cache/pnpm
      run: |
        echo "engine-strict = true" >> ~/.npmrc
        echo "cache-dir = $PNPM_ROOT/cache" >> ~/.npmrc
        echo "store-dir = $PNPM_ROOT/store" >> ~/.npmrc
        echo "state-dir = $PNPM_ROOT/state" >> ~/.npmrc

        echo "::set-output name=pnpm::$PNPM_ROOT"
        echo "::set-output name=corepack::$HOME/.node/corepack"

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: '16'
        # cache: pnpm

    - uses: actions/cache@v2
      with:
        path: ${{ steps.paths.outputs.pnpm }}
        key: ${{ runner.os }}-pnpm-v6-r3-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-v6-r3-

    - uses: actions/cache@v2
      with:
        path: ${{ steps.paths.outputs.corepack }}
        key: ${{ runner.os }}-corepack-r1-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-corepack-r1-

    - run: corepack enable

    - run: pnpm install
    - run: pnpm run -- build --minify ./dist/
      env:
        NODE_ENV: production

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
