# yaml-language-server: schema=https://json.schemastore.org/github-action

name: Build
on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - run: pnpm install
    - run: pnpm build --minify ./dist/
      env:
        NODE_ENV: production

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
