# yaml-language-server: schema=https://json.schemastore.org/github-action

name: Build
on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: pnpm
      env:
        PNPM_ROOT: ${{ runner.temp }}/.cache/pnpm
      run: |
        echo "engine-strict = true" >> ~/.npmrc
        echo "cache-dir = $PNPM_ROOT/cache" >> ~/.npmrc
        echo "store-dir = $PNPM_ROOT/store" >> ~/.npmrc
        echo "state-dir = $PNPM_ROOT/state" >> ~/.npmrc

        echo "::set-output name=root::$PNPM_ROOT"

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/cache@v2
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm.outputs.root }}
        key: ${{ runner.os }}-pnpm-v6-r2

    - name: install pnpm
      run: curl -L https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

    - run: pnpm install
    - run: pnpm build --minify ./dist/

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
